apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongoexpress.fullname" . }}
  labels:
    {{- include "mongoexpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30000
      protocol: TCP
      name: http
  selector: 
    {{- include "mongoexpress.selectorLabels" . | nindent 4 }}