apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql 
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: {{ .Release.Name }}-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
