apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysqldb.fullname" . }}
  labels:
    {{- include "mysqldb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    {{- include "mysqldb.selectorLabels" . | nindent 4 }}