apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  orgName: {{ .Values.orgName }}
  bucketName: {{ .Values.bucketName }}